### ISSUE TITLE
Consider using Codecov for both Go and Rust coverage

### ISSUE THREAD

**Issue by tjanez** [oasislabs/oasis-core#2655]
##### SUMMARY

It looks like [Codecov has support for reporting multiple different code coverages via so-called Flags](https://docs.codecov.io/docs/flags).

Example from their docs:
```yaml
coverage:
  status:
    project:
      default: off
      frontend:
        flags: frontend
      backend:
        target: 50%
        flags: backend
      api:
        target: 89%
        flags: api

flags:
  # filter the folder(s) you wish to measure by that flag
  backend:
    # only include files in the backend folder
    paths:
      - app/backend/
  frontend:
    paths:
      - app/frontend/
  api:
    paths:
      - app/api/
  tests:
    paths:
      - tests/
```

And one can also [get a different status badge for each Flag](https://community.codecov.io/t/badges-for-flags/270).

We could use this functionality to migrate the Rust coverage from Coveralls to Codecov.

##### ISSUE TYPE
- Ops
