### ISSUE TITLE
metrics.labels not parsed correctly for .yml configs

### ISSUE THREAD

**Issue by matevz** [oasislabs/oasis-core#2905]
Running `oasis-node --metrics.labels foo1=bar1,foo2=bar2` works. However, making a yaml file:
```
metrics:
  labels:
    foo1: bar1
    foo2: bar2
```
complains that no labels have been passed.

This regression was caused by #2687.
